package openapi

import (
	"encoding/json"
	"net/http"
)

// Document represents a simplified OpenAPI 3.0 specification.
type Document struct {
	OpenAPI string                 `json:"openapi"`
	Info    map[string]interface{} `json:"info"`
	Paths   map[string]interface{} `json:"paths"`
}

// Handler returns the OpenAPI specification as JSON.
func Handler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		Spec(w, r)
	})
}

// Spec writes the generated JSON OpenAPI document.
func Spec(w http.ResponseWriter, r *http.Request) {
	doc := Document{
		OpenAPI: "3.0.0",
		Info: map[string]interface{}{
			"title":       "{{.ProjectName}}",
			"version":     "1.0.0",
			"description": "Generated by FGOTHS Framework",
		},
		Paths: map[string]interface{}{
			"/health": map[string]interface{}{
				"get": map[string]interface{}{
					"summary": "Health check",
					"responses": map[string]interface{}{
						"200": map[string]interface{}{
							"description": "Service is up",
						},
					},
				},
			},
			"/metrics": map[string]interface{}{
				"get": map[string]interface{}{
					"summary": "Prometheus metrics",
					"responses": map[string]interface{}{
						"200": map[string]interface{}{
							"description": "Metrics endpoint",
						},
					},
				},
			},
		},
	}

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(doc)
}

// Docs renders a tiny Swagger-style landing page for the generated API.
func Docs(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(`
		<!doctype html>
		<html>
		<head><meta charset="utf-8"><title>{{.ProjectName}} API Docs</title></head>
		<body>
			<h1>{{.ProjectName}} API Docs</h1>
			<ul>
				<li><a href="/openapi.yaml">OpenAPI spec</a></li>
				<li><a href="/health">Health</a></li>
				<li><a href="/metrics">Metrics</a></li>
			</ul>
		</body>
		</html>`))
}
