// Code generated by fgoths; DO NOT EDIT.
// Regenerated by `fgoths generate crud` — mounts every generated entity.
package handlers

import (
	"database/sql"
	"net/http"
)

// RegisterCRUDRoutes mounts CRUD endpoints. Empty until you run
// `fgoths generate crud Entity field:type ...`.
func RegisterCRUDRoutes(mux *http.ServeMux, db *sql.DB) {
	if db == nil {
		return
	}
	// registerEntityRoutes(mux, db)
}
