// Code generated by fgoths; DO NOT EDIT.
// Regenerated by `fgoths generate crud` — mounts every generated entity.
package handlers

import (
	"database/sql"

	"{{.ProjectName}}/pkg/runtime"
)

// RegisterCRUDRoutes mounts CRUD endpoints. Empty until you run
// `fgoths generate crud Entity field:type ...`.
func RegisterCRUDRoutes(registrar runtime.Registrar, db *sql.DB) {
	if db == nil {
		return
	}
	// registerEntityRoutes(registrar, db)
}
