// Copyright (c) 2026, srars-tech
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// routeEntry is one HTTP route discovered by statically scanning the
// project's Go source for `mux.Handle`/`mux.HandleFunc` registrations.
type routeEntry struct {
	Method string
	Path   string
	File   string
	Line   int
}

var muxRegisterPattern = regexp.MustCompile(`mux\.(?:HandleFunc|Handle)\(\s*"([^"]+)"`)

// RunRoutes scans the current generated project for registered HTTP routes
// and prints them, similar in spirit to `artisan route:list`. It is a static
// scan of `mux.Handle`/`mux.HandleFunc` call sites, not a running server.
func RunRoutes(args []string) {
	if _, err := os.Stat("go.mod"); err != nil {
		fmt.Println("❌ go.mod not found; run this inside a generated project")
		fmt.Println("   Next step: cd into the project generated by `fgoths init`.")
		return
	}

	routes, err := scanRoutes(".")
	if err != nil {
		fmt.Printf("❌ Could not scan routes: %v\n", err)
		return
	}
	if len(routes) == 0 {
		fmt.Println("No routes found.")
		fmt.Println("   Next step: register a handler with mux.HandleFunc(\"METHOD /path\", ...) or run `fgoths generate crud`.")
		return
	}

	sort.Slice(routes, func(i, j int) bool {
		if routes[i].Path != routes[j].Path {
			return routes[i].Path < routes[j].Path
		}
		return routes[i].Method < routes[j].Method
	})

	methodWidth, pathWidth := len("METHOD"), len("PATH")
	for _, route := range routes {
		if len(route.Method) > methodWidth {
			methodWidth = len(route.Method)
		}
		if len(route.Path) > pathWidth {
			pathWidth = len(route.Path)
		}
	}

	fmt.Printf("%-*s  %-*s  %s\n", methodWidth, "METHOD", pathWidth, "PATH", "SOURCE")
	for _, route := range routes {
		fmt.Printf("%-*s  %-*s  %s:%d\n", methodWidth, route.Method, pathWidth, route.Path, route.File, route.Line)
	}
}

// scanRoutes walks root looking for mux.Handle/mux.HandleFunc registrations
// in non-test Go source files.
func scanRoutes(root string) ([]routeEntry, error) {
	var routes []routeEntry
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			if shouldSkipWatchDir(filepath.Base(path)) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		for lineNumber, line := range strings.Split(string(content), "\n") {
			match := muxRegisterPattern.FindStringSubmatch(line)
			if match == nil {
				continue
			}
			method, routePath := "ANY", match[1]
			if parts := strings.SplitN(match[1], " ", 2); len(parts) == 2 {
				method, routePath = parts[0], parts[1]
			}
			routes = append(routes, routeEntry{Method: method, Path: routePath, File: filepath.ToSlash(path), Line: lineNumber + 1})
		}
		return nil
	})
	return routes, err
}
